= GRUNDREGELN UND TECHNIK DES SPORTKEGELNS
ifndef::imagesdir[:imagesdir: images]
Luis Lair
:toc: left
:toclevels: 1

== DIE EINSTELLUNG DES KEGLERS ZU BEGINN UND WÄHREND DES WETTKAMPFES

Die richtige Einstellung zu einem Kegelwettkampf läßt sich nur durch völlige Konzentration auf die vor einem liegende Aufgabe erreichen. Auch im weiteren Verlauf des Kampfes soll man es streng vermeiden mit Freunden und Partnern oder gar mit Zuschauern zu sprechen oder deren eventuelle Kommentare zu beachten.

Der Spieler muss sich auch in der Zeitspanne zwischen zwei Würfen ganz auf den Ablauf des Spieles konzentrieren. Gerade dieser Zeitraum soll mit Überlegungen folgender Art ausgefüllt sein:

* Nach dem Schub vorne auf der Bohle stehen bleiben.
* Überprüfen, ob der Lauf, der Kugelaufzug, die
Auflage richtig war.
* Konzentriert den Lauf der Kugel verfolgen und beobachten, wie diese sich in ihrem Lauf auf der Bahn verhält.
* Beachten, wie die Kugel schlägt.

Aus der Summe dieser Beobachtungen kann man oft schon Rückschlüsse auf die Bahn ziehen, oder auch eigene Fehler erkennen.

Eine Beratung mit dem Sekundanten, um sich
seine Beobachtungen bestätigen zu lassen, ist
sicherlich von Vorteil. In der Praxis rechnet
man damit, dass sich ein Spieler nach 5 Wurf
auf die Bahn eingestellt hat. Zum Abstellen
eines Fehlers braucht ein Kegler, unterstützt
von seinem Sekundanten ca.3 Wurf.


== 1. GRUNDREGEL - Stand- u. Körperhaltung

*Der Grundstand in die Volle: linker Fuß steht neben der Aufsatzbohle, rechter Fuß steht auf der Aufsatzbohle, die Füße sind geschlossen und zeigen Richtung Kegel Nr.1 (Rechtshänder). Der
Körper ist leicht nach vorne
geneigt.*

=== KÖRPERHALTUNG BEIM ANLAUF

1. Schritt: Körper mitnehmen - Schulter waagrecht - nicht im Knie einsacken.

2. Schritt: Körper bleibt vorgeneigt - Schultern waagrecht - Körper und Knie annähernd gleiche Höhe wie bei Schritt 1.

3. Schritt: Körper mitnehmen in die Auflage - linkes Knie abbiegen, dabei Schultern waagrecht - Schulterpartie und gewünschte Laufrichtung der Kugel zum Kegel bilden einen rechten Winkel.
+
2 Winkel - Winkel zwischen Ober-
körper und linkem Oberschenkel ist
klein. Winkel zwischen ausgestrecktem
Arm und Oberkörper ist groß.

4. Schritt: Beendet den Anlauf - Rechter
Arm Richtung Kegel - Körper aufrichten - Blick zum Kegel - Ruhestellung.

== 2. GRUNDREGEL - Kugelführung u. Armhaltung

*3 Punktehaltung, der Mittelfinger liegt im Schwerpunkt. Daumen und Kleinfinger liegen links und rechts der Kugel, die Finger sind gespreizt - Arm leicht nach vorne.*

1. Schritt: Kugel vorn neben dem Körper halten, Arm bewegt sich leicht nach vorne um Rhythmus einzuleiten, gerader Aufzug nach rückwärts/(Hose streifen). Ellbogen gerade,

2. Schritt : Kugel nicht zu tief - Kugel neben
dem Körper - Ellbogen und Hand bilden
eine Linie zum anzuspielenden Kegel.

3. Schritt: Kugel durchziehen in die Auflage - Arm ausstrecken - Ellbogen innen - Arm bleibt tief - Handfläche in Richtung Gasse - Arm durchziehen - Hand offen (Finger) Kugelführung bei ausgestrecktem
Arm.


== 3. GRUNDREGEL - Anlauf

*Gerader Lauf - 4 Schritte - Richtung zum anzuspielenden Kegel, 1.Schritt Tempo langsam*

1. Schritt: Tempo langsam mit dem linken
Fuß beginnend - bei Mitnahme des Oberkörpers, der rechte Arm bewegt sich leicht nach vorn um Rhythmus einzuleiten,

2. Schritt: Mit Beginn des 2ten Schrittes wird der rechte Arm nach rückwärts aufgezogen, linker Arm dient zum Halten des Gleichgewichts.

3. Schritt: Abwurfphase - mit vor- und ausgestrecktem Arm und vorgeneigtem Oberkörper - Kugel zum Aufsatzpunkt bringen.

4. Schritt: Beendet den Anlauf - Rechter Arm Richtung Kegel - Körper aufrichten - Blick zum Kegel - Ruhestellung.

== 4. GRUNDREGEL - Kugelauflage

*Kugel muss beim Abwurf ruhig Mitte (2 cm links oder 2 cm rechts der Bohlenmitte) Bohle aufgesetzt werden - die Hand zum anzuspielenden Kegel führen.*

== 5. GRUNDREGEL - Gasse - Volle - Abräumen

*Erfolgt durch Standveränderung, wobei die Körperquerachse mit der Kugellaufrichtung zum Kegel einen rechten Winkel bilden muss.*

* *Rechte Gasse*: Vom Grundstand aus geringfügig von der Bohle nach links - Auflagemitte - Lauf zur Auflage. Handfläche nach oben, Ellbogen innen - (in Laufrichtung der Kugel zur Gasse)

* *Linke Gasse*: Vom Grundstand aus geringfügig in die Bohle nach rechts, Körper darf beim Abwurf nicht verdreht werden - Hand leicht aufgedreht, Lauf: 1. und 2. Schritt nach linker Bohlenspitz - Tempo langsam, Handfläche nicht überdrehen, Auflage
Mitte mit ausgestrecktem Arm.

=== Einzelne Kegel

* *Kegel 5 und 9*
+
Grundstand - Schub und Lauf gleich wie auf Kegel 1.

* Rechts : *Kegel 3 und 8*
+
Vom Grundstand aus ca.1/2 Fußbreite von den Bohlen wegstellen. Kugel muss die Bohlen in der Bohlenmitte verlassen. Handführung genau zum Kegel.

* *Kegel 6*
+
Vom Grundstand aus ca. 1 Fußbreite von der Bohle wegstellen. Kugel muss die Bohle in der Bohlenmitte verlassen. Handführung zum Kegel.

* Links : *Kegel 2 und 7*
+
Vom Grundstand aus in die Bohle hereinstellen, linke Schuhspitze soll mit linker Bohlenkante abschließen. Kugel muss Bohle in der Bohlenmitte verlassen. Lauf zum linken Ladenspitz. Handführung zum Kegel.

* *Kegel 4*
+
Vom Grundstand aus in die Bohle hereinstellen. Ca.1/2 Fußbreite weiter herein wie bei Kegel 2 u.7. Kugel muß Bohle in Bohlenmitte verlassen. Lauf zum linken
Bohlenspitz. Handführung zum Kegel.

=== FEHLER, FOLGEN und KORREKTUREN


|===
|Fehler |Folge |Korrektur / Grund


|FEHLER: Im Lauf den 1. oder 2, Schritt nicht gerade nach vorne gesetzt,

|FOLGE: Kugelaufzug nicht neben dem Körper, Kugel muss von außen hereingezogen werden, daher Auflage einmal links oder rechts von der Mitte, keine von der Mitte zur Gasse laufende Kugel.

|


|FEHLER: Kniestellung im 2. Schritt zu tief.
|FOLGE: Die Kugel kommt beim 3, Schritt zu tief zur Auflage, dadurch wird die Kugel zu kurz gelegt und läuft nicht präzise.

|

|FEHLER: Beim 3. Schritt (Ausfallschritt) das linke Knie nicht genügend abwinkeln, dafür das rechte Knie stärker beugen.

|FOLGE: Linke Schulter kommt hoch, rechte Schulter ganz tief, Schultern also nicht mehr waagrecht und damit auch keine gerade Hand- und Kugelführung.

|

|FEHLER: Aufrichten des Körpers während des 3. Schrittes.

|FOLGE: Kugel wird nach oben gezogen, keine von der Hand rollende Kugel, unsichere Kugelauflage.

|GRUND: Kugel wurde nicht zwischen 1. und 2. Schritt aufgezogen, Oberkörper ist bereits vorne, Kugel ist noch rückwärts oben. Die Kugel muss mit Kraft gezogen werden und so kommt es zum Aufrichten des Körpers.

|FEHLER: Körper fällt beim 4. Schritt (Nachlaufschritt) von der Bohle / rechter Fuß setzt nicht auf der Bohle auf!

|FOLGE: Keine gerade Körperhaltung zum Kegel und keinen (von der Mitte aus) geraden Kugellauf.

|GRUND: Kugelaufzug zu spät, die ganze Kraft liegt im 3. Schritt und die Kugel reißt den Körper mit.

KORREKTUR: Früherer Kugelaufzug; beim 4. Schritt (Nachlaufschritt) mit rechtem Fuß Kugelauflage zudecken; oder beim 3. Schritt linkes Knie stärker abwinkeln.

|FEHLER: Kein gerader Kugelaufzug, Handstellung einwärts, Ellbogen nach außen gedreht,

|FOLGE: Es entsteht ein Bogenschub, die Kugel wird nicht gerade neben dem Körper geführt, sondern vor dem Körper hereingezogen, dadurch Auflage links.

|KORREKTUR: Ellbogen beim Kugelaufzug nicht nach außen drehen. Auf- und Durchzug neben dem Körper. Handfläche nach oben, Fingerspitzen nach vorne zum Kegel gerichtet.

|FEHLER: Auslassen der Kugel auf einem Fuß (3. Schritt)

|FOLGE: Die Kugel verliert die Führung und bringt durch ihren Schwung den Körper aus dem Gleichgewicht, Auflage, Handführung, Körperhaltung werden unruhig.

|KORREKTUR: Nach dem 3. Schritt (Ausfallschritt)
den rechten Fuß sofort nachziehen. Fest auf
beiden Beinen stehen.

|FEHLER: Kugel zu lang gelegt.

|FOLGE: Körper wird abgedreht, linke Schulter kommt nach rückwärts, Handrücken der Wurfhand dreht dadurch nach oben.

|

|FEHLER: Beim 3. Schritt Ellbogen abwinkeln, Handfläche und Finger nach oben ziehen,

|FOLGE: Keine rollende Kugel, verhaltener gehobener Schub, keine sichere Auflage.

|GRUND: Zu später Kugelaufzug.

KORREKTUR: Finger öffnen und ausstrecken, Ellbogen strecken, auch wenn die Kugel bereits von der Hand gegangen ist.

|===

=== WIE SOLLEN LÄNGE DER SCHRITTE BEIM LAUF UND DESSEN GESCHWINDIGKEIT SEIN?

1. Die *SCHRITTLÄNGE* soll so sein, dass das Gleichgewicht während des Laufes nicht verloren geht.

2. Die *LÄNGE UND SCHNELLIGKEIT* der Schritte sollen so abgestimmt sein, dass der Kegler genügend Zeit und Raum hat, die Kugel im richtigen Rhythmus auf- und durchzuziehen.

3. *SCHRITT EINS UND ZWEI* müssen längenmäßig und zeitlich so eingeteilt werden, dass der Kegler gleichzeitig mit dem 3. Schritt (Ausfallschritt) die Kugel in die Auflage bringt (von der Hand).

4. Das *EXAKTE ZUSAMMENWIRKEN* von Schrittlänge und Geschwindigkeit ergibt für jeden Kegler den so wichtigen Rhythmus im Spiel.